version: "3"
services:

  vscoderemote:
    build:
      context: ./app-workspace/.devcontainer
    container_name: VScodeDevRemoteContainer
    ports:     
      - "3000:3000"
    volumes:
      - ./app-workspace:/workspace/
    tty: true
    networks:
      - mynetwork

  sonarqube:
    build:
      context: ./sonarqube
    container_name: sonarqube
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./volumes/sonarqube/conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres
    container_name: postgre
    networks:
      - mynetwork
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./volumes/sonarqube-db/data:/var/lib/postgresql/data

  jenkins:
      build:
          context: ./jenkins
      container_name: jenkins
      privileged: true
      user: root
      networks:
          - mynetwork
      volumes:
          - ./volumes/jenkins/jenkins_home:/var/jenkins_home
          - ./jenkins/jenkins_as_code/conf:/var/jenkins_conf
          - ./app-workspace:/var/lib/jenkins/repo
          - /var/run/docker.sock:/var/run/docker.sock
          - ./jenkins/jenkins_as_code/jobs/:/var/jenkins_home/jobs/
      ports:
          - "8000:8080"
      environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf

networks:
  mynetwork:
      driver: bridge
  
